# Generated by Django 5.1 on 2024-09-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donar',
            name='name',
            field=models.CharField(db_index=True, max_length=200, null=True, unique=True),
        ),
    ]
