# Generated by Django 5.1 on 2024-08-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0003_donar_alter_patient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donar',
            name='volume',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
